fixtures:
  repositories:
    stdlib:
      repo:  "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.6.0"
    ntp:
      repo: "https://github.com/puppetlabs/puppetlabs-ntp.git"
      ref: "4.2.0"
    profile_base: "https://github.com/relybv/dirict-profile_base.git"
    profile_apache: "https://github.com/relybv/dirict-profile_apache.git"
    rspec_monitor: "git://github.com/pgomersbach/test-rspec_monitor.git"
    apache: "https://github.com/puppetlabs/puppetlabs-apache.git"
    concat:
      repo: "git://github.com/puppetlabs/puppetlabs-concat.git"
      branch: "1.2.x"
    rsyslog: "https://github.com/saz/puppet-rsyslog.git"
    nfs: "https://github.com/echocat/puppet-nfs.git"
    motd: "https://github.com/puppetlabs/puppetlabs-motd.git"
    wget: "https://github.com/maestrodev/puppet-wget.git"
    gai: "https://github.com/smoeding/puppet-gai.git"

  symlinks:
    role_appl: "#{source_dir}"
