fixtures:
  repositories:
    stdlib:
      repo:  "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    apt : "https://github.com/puppetlabs/puppetlabs-apt.git"
    ntp:
      repo: "https://github.com/puppetlabs/puppetlabs-ntp.git"
      ref: "4.2.0"
    profile_base: "https://github.com/relybv/dirict-profile_base.git"
    profile_apache: "https://github.com/relybv/dirict-profile_apache.git"
    profile_redis: "https://github.com/relybv/dirict-profile_redis.git"
    rspec_monitor: "git://github.com/pgomersbach/test-rspec_monitor.git"
    telegraf: "https://github.com/datacentred/puppet-telegraf.git"
    profile_telegraf: "https://github.com/relybv/rely-profile_telegraf.git"
    profile_beats: "https://github.com/relybv/rely-profile_beats.git"
    filebeat: "https://github.com/pcfens/puppet-filebeat.git"
    profile_mcollective: "https://github.com/relybv/rely-profile_mcollective.git"
    rabbitmq: "https://github.com/puppetlabs/puppetlabs-rabbitmq.git"
    staging: "git://github.com/voxpupuli/puppet-staging.git"
    erlang: "git://github.com/garethr/garethr-erlang.git"
    apache: "https://github.com/puppetlabs/puppetlabs-apache.git"
    concat:
      repo: "git://github.com/puppetlabs/puppetlabs-concat.git"
      branch: "1.2.x"
    rsyslog: "https://github.com/saz/puppet-rsyslog.git"
    nfs: "https://github.com/echocat/puppet-nfs.git"
    motd: "https://github.com/puppetlabs/puppetlabs-motd.git"
    wget: "https://github.com/maestrodev/puppet-wget.git"
    gai: "https://github.com/smoeding/puppet-gai.git"
    archive: "https://github.com/voxpupuli/puppet-archive.git"

  symlinks:
    role_appl: "#{source_dir}"
